spring:
  profiles:
    active: dev
  application:
    name: sscs
  datasource:
    driver-class-name: ${sscs.sky.datasource.driver-class-name}
    url: ${sscs.sky.datasource.url}
    username: ${sscs.sky.datasource.username}
    password: ${sscs.sky.datasource.password}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

sscs:
  jwt:
    adm-secret: XYxHKvWpyoRQEhjfpHoLtiSDdgR4R8hN3abhFnK25sLKUDcl
    adm-token-name: adm_token
    stu-secret: cMCuHis0CrVPq7Q6xJgvoRRQ3Al6Z9ckyLnhmNxeUxBJ3QQf
    stu-token-name: stu_token
    tea-secret: Ih0Lgwtobr0DSJWpAIXWQ1fY0AJRnAMEoFwS3BxszdhLLAzc
    tea-token-name: tea_token
    # jwt过期时间(单位：毫秒）
    ttl-millis: 7200000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: '管理员端接口'
      paths-to-match: '/adm/**'
      packages-to-scan: cn.edu.ustc.sscs.controller.administrator
    - group: '学生端接口'
      paths-to-match: '/stu/**'
      packages-to-scan: cn.edu.ustc.sscs.controller.student
    - group: '教师端接口'
      paths-to-match: '/tea/**'
      packages-to-scan: cn.edu.ustc.sscs.controller.teacher

knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: 123456
  production: false

logging:
  level:
    cn:
      edu:
        ustc:
          sscs:
            mapper: debug
            controller: info
            service: info